####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |  HammyWands, Creating amazing spells to destroy the wizards.                                 | #
# |                                                                                              | #
# |                                                                                              | #
# |  DISCORD: https://discord.gg/D3NG9Yz                                                         | #
# |  AUTHOR: https://www.spigotmc.org/members/552330/                                            | #
# |  CONFIG CREATED ON VERSION: 1.0-B                                                            | #
# |                                                                                              | #
# |  Thank you for using HammyWands by Hammynl, It is very very much appreciated		         | #
# |  Need support? Feel free to join my development discord. Link is above		                 | #
# |  Have any suggestions? Feel free to leave them in the discord server!			             | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Wands are disabled here
disabled-worlds:
  - randomworld
  - addyourworldshere
# Cooldown settings, If the option is set to false, The value will not be counted. 
# If you wish to have no cooldown [NOT RECOMMENDED!] set length to 0 or set enabled to false.
# All of this is triggered once the cooldown runs out.

use-spells:
  barrage: true
  escape: true
  fireball: true
  lightning: true
  teleport: true
  thunderball: true
  
wizardwand:
   lore:
   - "&d&oThe power of this wand is overwhelming."
   - "&d&oIt was used to destroy the evil."
   - "&d&oBut did not manage to save the loved."
   cooldown:
      enabled: true
      values:
         length: 2
         sound: "BLOCK_ANVIL_FALL"
         message: "&dCooldown expired, You can now use a spell again."
         effect: "DRAGON_BREATH"
      options:
         effect: true
         message: true
         sound: true

bloodmagic:
   lore:
   - "&c&oControlling blood is a powerful ability..."
   cooldown:
      enabled: true
      values:
         length: 2
         sound: "BLOCK_ANVIL_FALL"
         message: "&dCooldown expired, You can now use a spell again."
         effect: "DRAGON_BREATH"
      options:
         effect: true
         message: true
         sound: true
      