name: "HammyMagic"
description: "Fight people with strength and spells!"
version: "BETA-0.3"
author: "Hammynl"
main: "com.github.hammynl.hammymagic.Magic"
api-version: "1.13"
commands:
  magic:
    description: Obtain a wand
    usage: /<command> 


