####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |  HammyMagic, Creating amazing spells to destroy the wizards.                                 | #
# |                                                                                              | #
# |                                                                                              | #
# |  DISCORD: https://discord.gg/D3NG9Yz                                                         | #
# |  AUTHOR: https://www.spigotmc.org/members/552330/                                            | #
# |  CONFIG CREATED ON VERSION: 1.0-B                                                            | #
# |                                                                                              | #
# |  Thank you for using HammyWands by Hammynl, It is very very much appreciated!                | #
# |  Need support? Feel free to join my development discord. Link is above                       | #
# |  Have any suggestions? Feel free to leave them in the discord server!                        | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Want to disable the wand in a certain world? Add it in the list below!
disabled-worlds:
  - randomworld
  - addyourworldshere

# Want to disable a spell because it is too overpowered or not suiting your server?
# disable it in here! in this case false means it will not be used.
use-spells:
  barrage: true
  escape: true
  fireball: true
  lightning: true
  teleport: true
  thunderball: true
  spark: true
  
# Names for your spells. This is the item name of the blaze rod.
# Have you disabled one of the spells? Don't worry. It'll just ignore the name.
spell-names:
  barrage: "&6&o&lWizard Wand &7[Barrage]"
  escape: "&6&o&lWizard Wand &7[Escape]"
  fireball: "&6&o&lWizard Wand &7[Fireball]"
  lightning: "&6&o&lWizard Wand &7[Lightning]"
  teleport: "&6&o&lWizard Wand &7[Teleport]"
  thunderball: "&6&o&lWizard Wand &7[Thunderball]"
  spark: "&6&o&lWizard Wand &7[Spark]"
  
  
# Here you can configure the lore for the wand and if you would like a cooldown or not
# You can also add certain sounds or effects (Remember that Particles and Effects are different things!)
wizardwand:
   lore:
   - "&d&oThe power of this wand is overwhelming."
   - "&d&oIt was used to destroy the evil."
   - "&d&oBut did not manage to save the loved."
   cooldown:
      enabled: true
      values:
         length: 2
         sound: "BLOCK_ANVIL_FALL"
         message: "&dCooldown expired, You can now use a spell again."
         effect: "DRAGON_BREATH"
      options:
         effect: true
         message: true
         sound: true
      